import type { Product } from '@/types';
import { fragrances, palette, productImage, soyMaterials } from './_shared';

/** Décor and novelty candles — the everyday shelf-and-shelfie range. */
export const decorCandles: Product[] = [
  {
    slug: 'mini-blooming-jar-candle',
    name: 'Mini Blooming Jar Candle',
    category: 'decor-candles',
    shortDescription: 'A 30 ml jar with a 3D flower blooming inside. Burns 10–12 hours.',
    longDescription:
      'A little glass jar with a sculpted flower set into the surface of the wax, so it blooms as it burns. Ten to twelve hours of clean soy burn in a jar small enough to tuck into a hamper — our best value gift at ₹60.',
    price: 60,
    priceLabel: '₹60',
    bulkTiers: [
      { moq: 20, pricePerUnit: 55, label: 'MOQ 20 pieces' },
      { moq: 50, pricePerUnit: 50, label: '50 pieces and above' },
    ],
    materials: [...soyMaterials, 'Reusable glass jar'],
    burnTime: '10–12 hours',
    dimensions: '30 ml jar',
    colours: [palette.blush, palette.white, palette.sage, palette.butter, palette.sky],
    fragrances: fragrances.standard,
    customisable: true,
    leadTimeDays: 20,
    occasions: ['weddings-return-gifts', 'housewarming', 'diwali', 'valentines'],
    featured: true,
    badges: ['₹60', '10–12 hr burn'],
    images: [
      productImage(
        'mini-blooming-jar-candle',
        'Mini Blooming Jar Candle',
        'Single 30 ml jar candle held between two fingers, 3D flower facing camera. Include a lit version too.',
      ),
    ],
  },
  {
    slug: 'bubble-candle',
    name: 'Bubble Candle',
    category: 'decor-candles',
    shortDescription: 'The cube of soft bubbles that started every shelfie.',
    longDescription:
      'A sculptural cube of rounded bubbles in matte soy wax. Pick a colour to match the room — it earns its place on a coffee table long before it is ever lit.',
    price: 180,
    priceLabel: 'From ₹180',
    materials: soyMaterials,
    burnTime: '8–10 hours',
    dimensions: 'Approx. 6 cm cube',
    colours: [palette.white, palette.blush, palette.sage, palette.lilac, palette.butter, palette.terracotta],
    fragrances: fragrances.standard,
    customisable: true,
    leadTimeDays: 20,
    occasions: ['housewarming', 'valentines', 'weddings-return-gifts'],
    featured: false,
    images: [
      productImage('bubble-candle', 'Bubble Candle', 'Bubble candle on a stack of books beside a plant, soft window light, matte finish visible.'),
    ],
  },
  {
    slug: 'woven-heart-candle',
    name: 'Woven Heart Candle',
    category: 'decor-candles',
    shortDescription: 'A knit-texture heart that looks like it was crocheted, not poured.',
    longDescription:
      'A heart with a woven, knitted surface — the kind of texture that makes people reach out and touch it. Sweet on its own, lovely in a pair.',
    price: 160,
    priceLabel: 'From ₹160',
    materials: soyMaterials,
    burnTime: '6–8 hours',
    colours: [palette.blush, palette.white, palette.red, palette.butter],
    fragrances: fragrances.standard,
    customisable: true,
    leadTimeDays: 20,
    occasions: ['valentines', 'weddings-return-gifts', 'housewarming'],
    featured: false,
    images: [
      productImage('woven-heart-candle', 'Woven Heart Candle', 'Macro of the woven heart texture, raking light so the knit pattern casts shadow.'),
    ],
  },
  {
    slug: 'rose-teddy-heart-candle',
    name: 'Rose Teddy Heart Candle',
    category: 'decor-candles',
    shortDescription: 'A teddy made of roses, sitting in a heart. Yes, really.',
    longDescription:
      'A rose-covered teddy set inside a heart base — unapologetically sweet, and the piece that sells out every February. Choose blush, red or ivory.',
    price: 250,
    priceLabel: 'From ₹250',
    materials: soyMaterials,
    burnTime: '8–10 hours',
    colours: [palette.blush, palette.red, palette.white, palette.pink],
    fragrances: ['Rose', 'Vanilla', 'Mogra', 'Unscented'],
    customisable: true,
    leadTimeDays: 20,
    occasions: ['valentines'],
    featured: false,
    images: [
      productImage('rose-teddy-heart-candle', 'Rose Teddy Heart Candle', 'Rose teddy heart candle in an open gift box with a ribbon and card.'),
    ],
  },
  {
    slug: 'teddy-bear-candle',
    name: 'Teddy Bear Candle',
    category: 'decor-candles',
    shortDescription: 'A little bear in soy wax — a favourite for baby showers.',
    longDescription:
      'A softly sculpted teddy in pastel wax, small enough to hand out at a baby shower or naming ceremony and cute enough that nobody ever burns it.',
    price: 140,
    priceLabel: 'From ₹140',
    materials: soyMaterials,
    burnTime: '5–6 hours',
    colours: [palette.cocoa, palette.butter, palette.blush, palette.white],
    fragrances: fragrances.standard,
    customisable: true,
    leadTimeDays: 20,
    occasions: ['weddings-return-gifts', 'valentines'],
    featured: false,
    images: [
      productImage('teddy-bear-candle', 'Teddy Bear Candle', 'Three teddy candles in different pastels lined up on a cream cloth.'),
    ],
  },
  {
    slug: 'couple-candle',
    name: 'Couple Candle',
    category: 'decor-candles',
    shortDescription: 'Two hearts. One flame.',
    longDescription:
      'Two figures in an embrace, sculpted as a single piece so they share one wick — two hearts, one flame. A quietly romantic gift for an anniversary or a first home.',
    price: 300,
    priceLabel: 'From ₹300',
    materials: soyMaterials,
    burnTime: '10–12 hours',
    dimensions: 'Approx. 12 cm tall',
    colours: [palette.white, palette.blush, palette.terracotta, palette.sage],
    fragrances: fragrances.standard,
    customisable: true,
    leadTimeDays: 20,
    occasions: ['valentines', 'weddings-return-gifts', 'housewarming'],
    featured: true,
    badges: ['Two hearts, one flame'],
    images: [
      productImage('couple-candle', 'Couple Candle', 'Couple embrace candle, side profile, single strong side light casting a long soft shadow.'),
    ],
  },
  {
    slug: 'marble-effect-mini-jar-candle',
    name: 'Marble Effect Mini Jar Candle',
    category: 'decor-candles',
    shortDescription: 'Swirled two-tone wax in a mini jar — no two are alike.',
    longDescription:
      'Two colours swirled by hand as the wax sets, so every jar carries its own marbling. Popular as a corporate desk gift with a printed tag.',
    price: 90,
    priceLabel: 'From ₹90',
    bulkTiers: [{ moq: 20, pricePerUnit: 80, label: 'MOQ 20 pieces' }],
    materials: [...soyMaterials, 'Reusable glass jar'],
    burnTime: '12–14 hours',
    dimensions: '50 ml jar',
    colours: [palette.terracotta, palette.sage, palette.sky, palette.blush],
    fragrances: fragrances.standard,
    customisable: true,
    leadTimeDays: 20,
    occasions: ['housewarming', 'diwali', 'weddings-return-gifts'],
    featured: false,
    images: [
      productImage('marble-effect-mini-jar-candle', 'Marble Effect Mini Jar Candle', 'Four marbled jars in a row showing colour variation, overhead flat-lay.'),
    ],
  },
  {
    slug: 'layered-jar-candle',
    name: 'Layered Jar Candle',
    category: 'decor-candles',
    shortDescription: 'Poured in bands of colour, each with its own fragrance.',
    longDescription:
      'Poured in stages so the jar sets in clean bands of colour — and if you like, a different fragrance in each layer, revealing itself as it burns down.',
    price: 250,
    priceLabel: 'From ₹250',
    materials: [...soyMaterials, 'Reusable glass jar'],
    burnTime: '25–30 hours',
    dimensions: '150 ml jar',
    colours: [palette.saffron, palette.blush, palette.sage, palette.white],
    fragrances: fragrances.standard,
    customisable: true,
    leadTimeDays: 20,
    occasions: ['housewarming', 'diwali'],
    featured: false,
    images: [
      productImage('layered-jar-candle', 'Layered Jar Candle', 'Layered jar candle lit at dusk, colour bands clearly separated, warm interior background.'),
    ],
  },
  {
    slug: 'pillar-candle',
    name: 'Pillar Candle',
    category: 'decor-candles',
    shortDescription: 'A clean, classic pillar — the quiet one in every good room.',
    longDescription:
      'Simple soy pillars in three heights, unscented or lightly fragranced. The steady backdrop piece for a mandir shelf, a dining table or a styled tray.',
    price: 200,
    priceLabel: 'From ₹200',
    materials: soyMaterials,
    burnTime: '20–25 hours',
    dimensions: '10 / 15 / 20 cm',
    colours: [palette.white, palette.cream, palette.terracotta, palette.sage],
    fragrances: fragrances.standard,
    customisable: true,
    leadTimeDays: 20,
    occasions: ['housewarming', 'diwali', 'weddings-return-gifts'],
    featured: false,
    images: [
      productImage('pillar-candle', 'Pillar Candle', 'Three pillar candles of different heights grouped on a wooden tray, lit, low ambient light.'),
    ],
  },
  {
    slug: 'taper-candle',
    name: 'Taper Candle',
    category: 'decor-candles',
    shortDescription: 'Slim twisted tapers for the dinner table.',
    longDescription:
      'Hand-twisted tapers in soy wax, sold in pairs. Dress a dining table for a celebration, or pair them with a Lippan frame for a housewarming gift set.',
    price: 180,
    priceLabel: 'From ₹180 / pair',
    materials: soyMaterials,
    burnTime: '5–6 hours',
    dimensions: 'Approx. 25 cm tall',
    colours: [palette.white, palette.blush, palette.sage, palette.terracotta, palette.butter],
    fragrances: ['Unscented', 'Vanilla', 'Sandalwood'],
    customisable: true,
    leadTimeDays: 20,
    occasions: ['housewarming', 'valentines', 'weddings-return-gifts'],
    featured: false,
    images: [
      productImage('taper-candle', 'Taper Candle', 'Pair of twisted tapers in ceramic holders on a set dinner table, evening light.'),
    ],
  },
];
