import type { Product } from '@/types';
import { fragrances, palette, productImage, soyMaterials } from './_shared';

/** Floral soy wax — the everyday gifting and return-gift range. */
export const floralCandles: Product[] = [
  {
    slug: 'hibiscus-tlight-candle',
    name: 'Hibiscus T-light Candle',
    category: 'floral-candles',
    shortDescription: 'A touch of floral beauty, a glow of serenity.',
    longDescription:
      'Hibiscus blooms poured as floating t-lights, with petals that hold their shape as the wick burns down. Beautiful in an urli with water and marigold, and light enough on the pocket to order by the dozen.',
    price: 35,
    priceLabel: 'From ₹35',
    bulkTiers: [
      { moq: 20, pricePerUnit: 30, label: 'MOQ 20 pieces' },
      { moq: 50, pricePerUnit: 28, label: '50 pieces and above' },
    ],
    materials: soyMaterials,
    burnTime: '2–3 hours',
    dimensions: 'Approx. 5 cm bloom',
    colours: [palette.red, palette.pink, palette.saffron, palette.white, palette.lilac],
    fragrances: fragrances.floral,
    customisable: true,
    leadTimeDays: 20,
    occasions: ['diwali', 'housewarming', 'weddings-return-gifts'],
    featured: false,
    badges: ['Customisable'],
    images: [
      productImage(
        'hibiscus-tlight-candle',
        'Hibiscus T-light Candle',
        'Five hibiscus t-lights floating in a brass urli with water and marigold petals. Shot slightly overhead.',
      ),
    ],
  },
  {
    slug: 'daisy-candle',
    name: 'Daisy Candle',
    category: 'floral-candles',
    shortDescription: 'Cheerful daisy heads in soft pastels — simple, sunny, always liked.',
    longDescription:
      'A little cluster of daisies poured in pastel soy wax with a butter-yellow centre. Sweet on a bedside table, and one of our easiest pieces to scale for return gifts.',
    price: 50,
    priceLabel: 'From ₹50',
    materials: soyMaterials,
    burnTime: '3–4 hours',
    colours: [palette.white, palette.butter, palette.blush, palette.sky],
    fragrances: fragrances.floral,
    customisable: true,
    leadTimeDays: 20,
    occasions: ['weddings-return-gifts', 'housewarming', 'valentines'],
    featured: false,
    images: [
      productImage(
        'daisy-candle',
        'Daisy Candle',
        'Three daisy candles grouped on a white ceramic dish, soft daylight, cream backdrop.',
      ),
    ],
  },
  {
    slug: 'daisy-urli-candle',
    name: 'Daisy Urli Candle',
    category: 'floral-candles',
    shortDescription: 'A beautiful, budget-friendly return gift — daisies set in a mini urli.',
    longDescription:
      'Daisy blooms set into a miniature urli, ready to hand over as-is. Our most-ordered return gift: it looks considered, photographs beautifully on a gift table, and stays comfortably within a per-guest budget.',
    price: 60,
    priceLabel: 'From ₹60',
    bulkTiers: [
      { moq: 20, pricePerUnit: 55, label: 'MOQ 20 pieces' },
      { moq: 50, pricePerUnit: 50, label: '50 pieces and above' },
    ],
    materials: [...soyMaterials, 'Mini metal urli'],
    burnTime: '5–6 hours',
    dimensions: 'Approx. 8 cm urli',
    colours: [palette.white, palette.blush, palette.butter, palette.sage],
    fragrances: fragrances.floral,
    customisable: true,
    leadTimeDays: 20,
    occasions: ['weddings-return-gifts', 'housewarming', 'diwali'],
    featured: true,
    badges: ['Return gift favourite'],
    images: [
      productImage(
        'daisy-urli-candle',
        'Daisy Urli Candle',
        'A row of daisy urli candles lined up as return gifts with name tags. Shows scale and gift-readiness.',
      ),
    ],
  },
  {
    slug: 'tulip-bouquet-candle',
    name: 'Tulip Bouquet Candle',
    category: 'floral-candles',
    shortDescription: 'A bouquet that never wilts — available in more than ten colours.',
    longDescription:
      'A hand-tied cluster of tulips poured in soy wax and wrapped like a florist’s bouquet. Because your love deserves more than ordinary flowers — this one is still on the shelf next anniversary.',
    price: 350,
    priceLabel: 'From ₹350',
    materials: soyMaterials,
    burnTime: '10–12 hours',
    dimensions: 'Approx. 14 cm tall',
    colours: [palette.pink, palette.white, palette.saffron, palette.lilac, palette.red, palette.butter],
    fragrances: fragrances.floral,
    customisable: true,
    leadTimeDays: 20,
    occasions: ['valentines', 'weddings-return-gifts', 'housewarming'],
    featured: true,
    badges: ['10+ colours'],
    images: [
      productImage(
        'tulip-bouquet-candle',
        'Tulip Bouquet Candle',
        'Tulip bouquet candle held in one hand against a plain wall, wrap and ribbon visible. Signature hand-in-frame shot.',
      ),
    ],
  },
  {
    slug: 'rose-bouquet-candle',
    name: 'Rose Bouquet Candle',
    category: 'floral-candles',
    shortDescription: 'Roses in wax, wrapped and ribboned — romance that keeps.',
    longDescription:
      'A gathered posy of roses poured in blush and deep red, wrapped in tissue and tied with satin. Our most requested Valentine’s piece, and a lovely alternative to fresh flowers for a proposal or an anniversary table.',
    price: 350,
    priceLabel: 'From ₹350',
    materials: soyMaterials,
    burnTime: '10–12 hours',
    colours: [palette.red, palette.blush, palette.pink, palette.white],
    fragrances: ['Rose', 'Mogra', 'Vanilla', 'Unscented'],
    customisable: true,
    leadTimeDays: 20,
    occasions: ['valentines', 'weddings-return-gifts'],
    featured: false,
    images: [
      productImage(
        'rose-bouquet-candle',
        'Rose Bouquet Candle',
        'Rose bouquet candle on a marble surface with scattered dried petals and a lit taper behind.',
      ),
    ],
  },
  {
    slug: 'peony-candle',
    name: 'Peony Candle',
    category: 'floral-candles',
    shortDescription: 'Layered peony petals with a soft, sculptural bloom.',
    longDescription:
      'Ruffled peony petals built up layer by layer, so the bloom keeps its shape under warm light. A quiet, elegant piece for a dressing table or a styled shelf.',
    price: 220,
    priceLabel: 'From ₹220',
    materials: soyMaterials,
    burnTime: '8–10 hours',
    colours: [palette.blush, palette.white, palette.pink, palette.butter],
    fragrances: fragrances.floral,
    customisable: true,
    leadTimeDays: 20,
    occasions: ['valentines', 'housewarming', 'weddings-return-gifts'],
    featured: false,
    images: [
      productImage('peony-candle', 'Peony Candle', 'Single peony candle on a linen napkin, side-lit to show petal layers.'),
    ],
  },
  {
    slug: 'heart-rose-candle',
    name: 'Heart Rose Candle',
    category: 'floral-candles',
    shortDescription: 'A heart of roses — small enough to slip into a gift box.',
    longDescription:
      'Roses clustered into a heart, poured in blush or deep red. Small, sweet and easy to pair with a keepsake frame for an anniversary set.',
    price: 150,
    priceLabel: 'From ₹150',
    materials: soyMaterials,
    burnTime: '6–8 hours',
    colours: [palette.red, palette.blush, palette.pink, palette.white],
    fragrances: ['Rose', 'Vanilla', 'Mogra', 'Unscented'],
    customisable: true,
    leadTimeDays: 20,
    occasions: ['valentines', 'weddings-return-gifts'],
    featured: false,
    images: [
      productImage('heart-rose-candle', 'Heart Rose Candle', 'Heart rose candle in an open gift box with tissue, shot from above.'),
    ],
  },
  {
    slug: 'marigold-candle',
    name: 'Marigold Candle',
    category: 'floral-candles',
    shortDescription: 'The flower of every Indian celebration, poured in soy wax.',
    longDescription:
      'Marigold heads in saffron and orange — the flower that hangs over every doorway at festival time. Beautiful clustered on a pooja thali or floated in an urli with water.',
    price: 45,
    priceLabel: 'From ₹45',
    bulkTiers: [
      { moq: 20, pricePerUnit: 40, label: 'MOQ 20 pieces' },
      { moq: 50, pricePerUnit: 35, label: '50 pieces and above' },
    ],
    materials: soyMaterials,
    burnTime: '3–4 hours',
    colours: [palette.saffron, palette.orange, palette.butter, palette.red],
    fragrances: fragrances.festive,
    customisable: true,
    leadTimeDays: 20,
    occasions: ['ganesh-chaturthi', 'diwali', 'housewarming'],
    featured: false,
    images: [
      productImage('marigold-candle', 'Marigold Candle', 'Marigold candles beside real marigolds — the point is you cannot tell which is which.'),
    ],
  },
  {
    slug: 'floral-tlight-candles',
    name: 'Floral T-light Candles',
    category: 'floral-candles',
    shortDescription: 'Customisable in any colour and fragrance — square, round or heart.',
    longDescription:
      'Our workhorse return gift. Floral t-lights in your choice of shape, colour and fragrance, packed in sets and tagged with the host’s name if you like. Order twenty or two hundred.',
    price: 30,
    priceLabel: 'From ₹30',
    bulkTiers: [
      { moq: 20, pricePerUnit: 28, label: 'MOQ 20 pieces' },
      { moq: 50, pricePerUnit: 25, label: '50 pieces and above' },
    ],
    materials: soyMaterials,
    burnTime: '2–3 hours',
    dimensions: 'Square, round or heart',
    colours: [palette.white, palette.pink, palette.saffron, palette.sage, palette.sky, palette.lilac],
    fragrances: fragrances.floral,
    customisable: true,
    leadTimeDays: 20,
    occasions: ['weddings-return-gifts', 'diwali', 'housewarming', 'rakshabandhan'],
    featured: true,
    badges: ['From ₹30', 'Any colour'],
    images: [
      productImage(
        'floral-tlight-candles',
        'Floral T-light Candles',
        'Grid of floral t-lights in square, round and heart shapes across six colours. Flat-lay on cream.',
      ),
    ],
  },
];
