import type { Product } from '@/types';
import {
  fragrances,
  mithaiBulkTiers,
  mithaiColours,
  palette,
  productImage,
  soyMaterials,
} from './_shared';

/** The signature line — hyper-realistic Indian sweets sculpted in soy wax. */
export const mithaiCandles: Product[] = [
  {
    slug: 'modak-candle',
    name: 'Modak Candle',
    category: 'mithai-candles',
    shortDescription: 'Bappa’s favourite sweet, sculpted in soy wax and finished with silver varq.',
    longDescription:
      'The piece that started it all. Each modak is hand-moulded in 100% soy wax, demoulded one at a time and finished with real silver-varq detailing — so it sits on a pooja thali looking exactly like the real thing, until you light it. Choose your colours to match your décor, or keep it classic in ivory and saffron.',
    price: 40,
    priceLabel: 'From ₹30',
    bulkTiers: mithaiBulkTiers,
    boxOption: { pieces: 4, price: 185, label: 'Gift box of 4' },
    materials: soyMaterials,
    burnTime: '4–5 hours',
    dimensions: 'Approx. 4 cm × 4 cm',
    colours: mithaiColours,
    fragrances: fragrances.festive,
    customisable: true,
    leadTimeDays: 20,
    occasions: ['ganesh-chaturthi', 'diwali', 'weddings-return-gifts', 'housewarming'],
    featured: true,
    badges: ['Bestseller', 'Customisable'],
    images: [
      productImage(
        'modak-candle',
        'Modak Candle',
        'Three modak candles on a brass thali with marigold petals. Silver varq must read clearly — light from the side.',
      ),
      productImage(
        'modak-candle',
        'Modak Candle — lit',
        'The same modak lit in low light, flame visible, warm bokeh behind. Shows it is genuinely a candle.',
        { suffix: 'lit', aspect: '1:1' },
      ),
    ],
  },
  {
    slug: 'laddu-candle',
    name: 'Laddu Candle',
    category: 'mithai-candles',
    shortDescription: 'Textured besan-laddu realism, right down to the silver varq on top.',
    longDescription:
      'Hand-rolled in soy wax with the grainy texture of a real besan laddu, then topped with silver varq. Sold loose for hampers or in a four-piece window box that looks like it came straight from a sweet shop. A favourite for Diwali corporate gifting.',
    price: 40,
    priceLabel: 'From ₹30',
    bulkTiers: mithaiBulkTiers,
    boxOption: { pieces: 4, price: 185, label: 'Gift box of 4' },
    materials: soyMaterials,
    burnTime: '4–5 hours',
    dimensions: 'Approx. 4.5 cm diameter',
    colours: [palette.saffron, palette.butter, palette.orange, palette.white],
    fragrances: fragrances.festive,
    customisable: true,
    leadTimeDays: 20,
    occasions: ['diwali', 'ganesh-chaturthi', 'weddings-return-gifts', 'rakshabandhan'],
    featured: true,
    badges: ['Customisable'],
    images: [
      productImage(
        'laddu-candle',
        'Laddu Candle',
        'Four laddu candles in a window gift box, lid half open. Texture and silver varq must be sharp.',
      ),
    ],
  },
  {
    slug: 'kaju-katli-candle',
    name: 'Kaju Katli Candle',
    category: 'mithai-candles',
    shortDescription: 'Diamond-cut katli with a silver leaf finish, served on a wooden platter.',
    longDescription:
      'The clean diamond cut of kaju katli, complete with its silver leaf, poured in pale ivory soy wax. Sold as a set on a wooden platter — the piece guests always pick up before realising it is a candle.',
    price: 45,
    priceLabel: 'From ₹45',
    bulkTiers: [
      { moq: 20, pricePerUnit: 40, label: 'MOQ 20 pieces' },
      { moq: 50, pricePerUnit: 35, label: '50 pieces and above' },
    ],
    materials: soyMaterials,
    burnTime: '3–4 hours',
    dimensions: 'Approx. 5 cm × 3.5 cm diamond',
    colours: [palette.white, palette.cream, palette.butter],
    fragrances: fragrances.festive,
    customisable: true,
    leadTimeDays: 20,
    occasions: ['diwali', 'weddings-return-gifts', 'housewarming'],
    featured: true,
    images: [
      productImage(
        'kaju-katli-candle',
        'Kaju Katli Candle',
        'Six katli diamonds fanned on a round wooden platter, silver leaf catching the light. Overhead flat-lay.',
      ),
    ],
  },
  {
    slug: 'kesar-pedha-candle',
    name: 'Kesar Pedha Candle',
    category: 'mithai-candles',
    shortDescription: 'Saffron pedha with a pressed centre and delicate silver leaf.',
    longDescription:
      'Warm saffron soy wax pressed into the familiar pedha round, thumbed in the centre and finished with silver leaf. Scented in kesar-elaichi, it smells like a mithai box the moment it is lit.',
    price: 45,
    priceLabel: 'From ₹45',
    bulkTiers: [
      { moq: 20, pricePerUnit: 40, label: 'MOQ 20 pieces' },
      { moq: 50, pricePerUnit: 35, label: '50 pieces and above' },
    ],
    materials: soyMaterials,
    burnTime: '3–4 hours',
    dimensions: 'Approx. 4 cm diameter',
    colours: [palette.saffron, palette.butter, palette.white],
    fragrances: fragrances.festive,
    customisable: true,
    leadTimeDays: 20,
    occasions: ['diwali', 'ganesh-chaturthi', 'weddings-return-gifts'],
    featured: true,
    images: [
      productImage(
        'kesar-pedha-candle',
        'Kesar Pedha Candle',
        'A stack of three saffron pedha candles on a brass coaster, silver leaf visible, warm light.',
      ),
    ],
  },
  {
    slug: 'rasmalai-candle',
    name: 'Rasmalai Candle',
    category: 'mithai-candles',
    shortDescription: 'Served in a glass bowl — saffron, pistachio and rose petals.',
    longDescription:
      'Poured into a small glass bowl so it looks like rasmalai swimming in kesar milk, finished with pistachio slivers and rose petal detail — all in wax. Reusable bowl, refillable on request. The centrepiece of a festive hamper.',
    price: 120,
    priceLabel: 'From ₹120',
    materials: [...soyMaterials, 'Reusable glass bowl'],
    burnTime: '8–10 hours',
    dimensions: 'Approx. 8 cm glass bowl',
    colours: [palette.white, palette.saffron, palette.pista],
    fragrances: ['Kesar Elaichi', 'Rose', 'Vanilla', 'Unscented'],
    customisable: true,
    leadTimeDays: 20,
    occasions: ['diwali', 'ganesh-chaturthi', 'housewarming'],
    featured: true,
    badges: ['Hamper favourite'],
    images: [
      productImage(
        'rasmalai-candle',
        'Rasmalai Candle',
        'Glass bowl rasmalai candle shot at 45°, pistachio and rose petal detail sharp, cream fabric backdrop.',
      ),
    ],
  },
  {
    slug: 'mixed-mithai-bowl-candle',
    name: 'Mixed Mithai Bowl Candle',
    category: 'mithai-candles',
    shortDescription: 'A wooden bowl of assorted sweets — every one of them a candle.',
    longDescription:
      'An assortment of modak, laddu, katli and pedha arranged in a turned wooden bowl. Our most-gifted piece for housewarmings and Diwali hampers, because it reads as a bowl of mithai from across the room. Choose the mix and the colour story.',
    price: 450,
    priceLabel: 'From ₹450',
    materials: [...soyMaterials, 'Turned wooden bowl'],
    burnTime: '4–5 hours per piece',
    dimensions: 'Approx. 15 cm bowl, 6–8 pieces',
    colours: [palette.saffron, palette.white, palette.orange, palette.butter, palette.pink],
    fragrances: fragrances.festive,
    customisable: true,
    leadTimeDays: 20,
    occasions: ['diwali', 'ganesh-chaturthi', 'housewarming', 'weddings-return-gifts'],
    featured: true,
    badges: ['Gift-ready'],
    images: [
      productImage(
        'mixed-mithai-bowl-candle',
        'Mixed Mithai Bowl Candle',
        'Wooden bowl filled with assorted mithai candles, shot slightly overhead with marigolds and a diya alongside.',
      ),
    ],
  },
];
